name: CI+CD

on: [push]

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Setup .NET v7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    # PROD build
    - name: Build and publish with dotnet
      run: |
          dotnet build --configuration Release
          dotnet publish -c Release -o ./nebularApiApp 

    # Depending on what kind of build there's been, these would be unit or acceptance tests
    - name: PLACEHOLDER FOR FUTURE TESTS
      run: echo "Hello tests! (TODO)"

    # Deploy
    - name: Deploy to Azure web app
      uses: azure/webapps-deploy@v2
      with:
        app-name: nebularapi
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}    
        package: './nebularApiApp'
