name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101'
    - name: Build with dotnet
      run: dotnet build --configuration Release

  test:
    needs: build
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: PLACEHOLDER FOR FUTURE UNIT TESTS
      run: echo "Hello tests! (TODO)"

  deploy:
    needs: test
    name: Deploy to the cloud
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Azure web app
      uses: azure/appservice-actions/webapp@master
      with:
        app-name: nebularapi
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}    
